name: Lint

on: [push, pull_request]

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-pycodestyle:
    name: Code style check with pycodestyle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install pycodestyle
      run: pip install tox pycodestyle
    - name: Lint using pycodestyle
      run: tox -e pycodestyle-minimal
  lint-relint:
    name: Code style check with relint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install relint
      run: pip install tox relint
    - name: Lint using relint
      run: tox -e relint src/sage/
  lint-rst:
    name: Validate docstring markup as RST
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install tox
      run: pip install tox
    - name: Lint using tox -e rst
      run: tox -e rst
